# Auto-generated by .github/workflows/release.yml — do not edit by hand.
# Run: git push --tags v<version> to trigger an update.
{
  "x86_64-linux"  = { sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; url = ""; };
  "aarch64-linux" = { sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; url = ""; };
  "x86_64-darwin" = { sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; url = ""; };
  "aarch64-darwin"= { sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; url = ""; };
}
