#!/usr/bin/env ruby
# frozen_string_literal: true

# code: language=ruby

require_relative 'lib/servers'

def usage!
  puts <<~USAGE
    Usage: uninstall-servers [<server>...]
  USAGE

  exit 1
end

usage! if ARGV.empty?

Servers::Registry.servers_for_args(ARGV).each(&:uninstall)
