"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Miller's Vim RC File
"    working on _Learn VimScript the Hard Way_
"    http://learnvimscriptthehardway.stevelosh.com
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Ch 3, 5
:nnoremap - ddp
:nnoremap _ ddkP

set number
set ruler
