"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Miller's Vim RC File
"    working on _Learn VimScript the Hard Way_
"    http://learnvimscriptthehardway.stevelosh.com
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Ch 3, 5
:nnoremap - ddp
:nnoremap _ ddkP

" Ch 4-5
" Note that this mapping works for the 2nd-last character of a word
:inoremap <c-u> <esc>viwUea
:inoremap <c-l> <esc>viwuea
:nnoremap <c-u> viwUe
:nnoremap <c-l> viwue
